apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-dev-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: disk
---
apiVersion: v1
kind : PersistentVolumeClaim
metadata:
  name: postgres-dev-pvc
spec:
  storageClassName: ""
  volumeName: postgres-dev-pv
  accessModes:
    - ReadWriteOnce
  # DB가 요청할 볼륨의 리소스
  resources:
    requests:
      storage: 10G
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-dev-secret
stringData:
  POSTGRES_DB: test_dev
  POSTGRES_USER: test_dev
  POSTGRES_PASSWORD: test_dev
  PGDATA: /var/lib/postgresql/data/pgdata/dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-postgres-dev
  template:
    metadata:
      labels:
        app: db-postgres-dev
    spec:
      containers:
      - name: postgres
        image: postgres:13.3
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: postgres-dev-secret
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/dev
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-dev-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-dev-svc
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: db-postgres-dev